import { NextRequest, NextResponse } from "next/server";
import { createSupabaseAdminClient } from "@/lib/supabase/server";
import { orderSchema, validateForm } from "@/lib/validations";
import { sendOrderStatusUpdate } from "@/lib/email/send";
import { requireAdmin, rateLimit } from "@/lib/api-auth";

export async function POST(request: NextRequest) {
  const limited = rateLimit(request, { maxRequests: 10, windowMs: 60_000 });
  if (limited) return limited;

  const body = await request.json();

  // Validate required fields
  const validation = validateForm(orderSchema, {
    customerEmail: body.customerEmail,
    customerName: body.customerName,
    customerPhone: body.customerPhone,
    shippingAddress: body.shippingAddress,
  });

  if (!validation.success) {
    return NextResponse.json(
      { error: "Validation failed", details: validation.errors },
      { status: 400 }
    );
  }

  // Check items exist
  if (!Array.isArray(body.items) || body.items.length === 0) {
    return NextResponse.json(
      { error: "Order must contain at least one item" },
      { status: 400 }
    );
  }

  const orderData = {
    order_number: "", // Will be generated by DB trigger
    customer_email: body.customerEmail,
    customer_name: body.customerName,
    customer_phone: body.customerPhone ?? "",
    shipping_address: body.shippingAddress,
    items: body.items,
    subtotal: body.subtotal ?? 0,
    shipping_cost: body.shippingCost ?? 0,
    total: body.total ?? 0,
    status: "pending" as const,
    payment_status: "pending" as const,
    payment_method: "manual",
    notes: "",
  };

  try {
    const supabase = createSupabaseAdminClient();
    const { data, error } = await supabase
      .from("orders")
      .insert(orderData)
      .select("id, order_number")
      .single();

    if (error) {
      console.error("[api/orders] insert error:", error.message);
      return NextResponse.json(
        { error: "שגיאה ביצירת ההזמנה. נסי שנית." },
        { status: 500 }
      );
    }

    return NextResponse.json({
      orderId: data.id,
      orderNumber: data.order_number,
      status: "pending",
    });
  } catch {
    return NextResponse.json(
      { error: "שגיאת שרת ביצירת הזמנה." },
      { status: 500 }
    );
  }
}

const VALID_STATUSES = ["pending", "confirmed", "processing", "shipped", "delivered", "cancelled"] as const;

export async function PATCH(request: NextRequest) {
  const auth = await requireAdmin(request);
  if (!auth.authorized) return auth.response;

  const body = await request.json();
  const { id, status } = body;

  if (!id || typeof id !== "string") {
    return NextResponse.json({ error: "Missing order id" }, { status: 400 });
  }

  if (!status || !VALID_STATUSES.includes(status)) {
    return NextResponse.json(
      { error: `Invalid status. Must be one of: ${VALID_STATUSES.join(", ")}` },
      { status: 400 }
    );
  }

  try {
    const supabase = createSupabaseAdminClient();
    const { data, error } = await supabase
      .from("orders")
      .update({ status })
      .eq("id", id)
      .select("id, status")
      .single();

    if (error) {
      console.error("[api/orders] update error:", error.message);
      return NextResponse.json({ error: "Failed to update order" }, { status: 500 });
    }

    if (!data) {
      return NextResponse.json({ error: "Order not found" }, { status: 404 });
    }

    // Send status update email to customer (fire-and-forget)
    if (status !== "pending") {
      const { data: orderData } = await supabase
        .from("orders")
        .select("customer_email, customer_name, order_number")
        .eq("id", id)
        .single();

      if (orderData) {
        sendOrderStatusUpdate(
          orderData.customer_email,
          orderData.order_number,
          orderData.customer_name,
          status
        ).catch((err) => { console.error("[email] send failed:", err); });
      }
    }

    return NextResponse.json({ id: data.id, status: data.status });
  } catch {
    return NextResponse.json({ error: "Server error" }, { status: 500 });
  }
}

export async function GET(request: NextRequest) {
  const auth = await requireAdmin(request);
  if (!auth.authorized) return auth.response;

  try {
    const supabase = createSupabaseAdminClient();
    const { data, error } = await supabase
      .from("orders")
      .select("*")
      .order("created_at", { ascending: false })
      .limit(50);

    if (error) {
      return NextResponse.json({ orders: [], error: error.message }, { status: 500 });
    }

    return NextResponse.json({ orders: data });
  } catch (err) {
    console.error("[api/orders] GET error:", err);
    return NextResponse.json({ error: "שגיאה בטעינת הזמנות" }, { status: 500 });
  }
}
